################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3"

services:
  web:
   build: backend/.
   container_name: web
   ports:
   - "3000:3000"
   networks:
   - node-red-net
   environment:
   - VIRTUAL_HOST=develop.loc
   volumes:
   - ./backend:/usr/src/app
   restart: always
   depends_on:
   - redis
   - mongo
   - timescaledb 

  nodered:
   image: nodered/node-red-docker:latest
   container_name: nodered
   environment:
   - TZ=Europe/Kiev
   ports:
   - "1880:1880"
   networks:
   - node-red-net
   volumes:
   - ./nodered/data:/data
   restart: always
   depends_on:
   - redis
   - mongo
   - timescaledb  

  redis:
   image: redis
   command: ["redis-server", "--appendonly", "yes"]
   container_name: redis
   ports:
   - "6379:6379"
   networks:
   - node-red-net
   volumes:
   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
   - ./db/redis/data:/data     
   command:
   - /usr/local/etc/redis/redis.conf
   restart: always

  mongo:
   image: mongo
   container_name: mongodb   
   ports:
   - "27017:27017"
   networks:
   - node-red-net
   volumes:
   - ./db/mongodb/data:/data/db
   restart: always

  timescaledb:
   image: timescale/timescaledb:latest
   container_name: timescaledb
   ports:
   - "5432:5432"
   environment:
   - POSTGRES_PASSWORD=548987
   networks:   
   - node-red-net
   volumes:
   - ./db/timescaledb/data:/var/lib/postgresql/data
   restart: always

  pgadmin:
   image: dpage/pgadmin4 
   container_name: pgadmin  
   ports:
   - "5050:80"
   environment:
   - PGADMIN_DEFAULT_EMAIL=admin@domain.com
   - PGADMIN_DEFAULT_PASSWORD=548987  
   - SERVER_PORT=5050
   networks:
   - node-red-net
   volumes:
   - ./admin/pgAdmin4:/var/lib/pgadmin
   depends_on:
   - timescaledb      
   restart: always

  rabbitmq:
   image: rabbitmq:3-management
   container_name: rabbitmq
   hostname: rabbitmq_web
   volumes:
   - ./rabbitmq/etc/:/etc/rabbitmq/
   - ./rabbitmq/data/:/var/lib/rabbitmq/
   - ./rabbitmq/logs/:/var/log/rabbitmq/
   environment:
     RABBITMQ_ERLANG_COOKIE: cookie 
     RABBITMQ_DEFAULT_USER: user
     RABBITMQ_DEFAULT_PASS: password
   ports:
   - 5672:5672
   - 15672:15672
   networks:
   - node-red-net
   restart: always

  nginx:
   image: nginx:latest
   hostname: nginx
   container_name: nginx
   ports:
   - 80:80
   depends_on:
   - web
   volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   networks:
      node-red-net:
        ipv4_address: 10.0.0.10 

  redis-commander:
   container_name: redis-commander
   hostname: redis-commander
   image: rediscommander/redis-commander:latest
   restart: always
   depends_on:
   - redis
   environment:
   - REDIS_HOSTS=local:redis:6379
   ports:
   - "8081:8081"
   networks:
   - node-red-net

networks:
    node-red-net:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.0.0.0/24
