################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3"

services:
  nodered:
   image: nodered/node-red-docker:latest
   container_name: nodered
   environment:
   - TZ=Europe/Kiev
   ports:
   - "1880:1880"
   networks:
   - dealer-net
   volumes:
   - ./nodered/data:/data
   restart: always
   depends_on:
   - redis
   - postgres

  redis:
   image: redis
   command: ["redis-server", "--appendonly", "yes"]
   container_name: redis
   ports:
   - "6379:6379"
   networks:
   - dealer-net
   volumes:
   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
   - ./db/redis/data:/data     
   command:
   - /usr/local/etc/redis/redis.conf
   restart: always

  postgres:
   image: postgres
   container_name: postgres
   ports:
   - "5432:5432"
   environment:
   - POSTGRES_PASSWORD=548987
   networks:   
   - dealer-net
   volumes:
   - ./db/postgresql/data:/var/lib/postgresql/data
   restart: always

  pgadmin:
   image: dpage/pgadmin4 
   container_name: pgadmin  
   ports:
   - "5050:80"
   environment:
   - PGADMIN_DEFAULT_EMAIL=admin@domain.com
   - PGADMIN_DEFAULT_PASSWORD=548987  
   - SERVER_PORT=5050
   networks:
   - dealer-net
   # volumes:
   # - ./admin/pgAdmin4:/var/lib/pgadmin
   depends_on:
   - postgres      
   restart: always

  nginx:
   image: nginx:latest
   hostname: nginx
   container_name: nginx
   ports:
   - 80:80
   depends_on:
   - redis-commander
   - nodered
   volumes:
   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
   networks:
      dealer-net:
        ipv4_address: 10.0.0.10 

  redis-commander:
   container_name: redis-commander
   hostname: redis-commander
   image: rediscommander/redis-commander:latest
   restart: always
   depends_on:
   - redis
   environment:
   - REDIS_HOSTS=local:redis:6379
   ports:
   - "8081:8081"
   networks:
   - dealer-net

networks:
   dealer-net:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 10.0.0.0/24
