################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "2"

services:
  node-red:
    image: nodered/node-red-docker:latest
    container_name: nodered
    environment:
      - TZ=Europe/Kiev
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red/data:/data
    depends_on:
      - redis
      - mongo
    
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    container_name: redis
    ports:
     - "6379:6379"
    networks:
     - node-red-net
    volumes:
     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
     - ./db/redis/data:/data     
    command:
     - /usr/local/etc/redis/redis.conf
      
  mongo:
   image: mongo
   container_name: mongodb   
   ports:
    - "27017:27017"
   networks:
    - node-red-net
   volumes:
    - ./db/mongodb/data:/data/db
           
networks:
  node-red-net:
